### ISSUE TITLE
Local WebServer - Doesn't load looking for commitUrl

### ISSUE THREAD

**Issue by iBotPeaches** [N0MoreSecr3ts/wraith#102]
I enabled the web-server output while loading a local repo.

I got the following console crash.

```
VM140:16 Uncaught ReferenceError: CommitUrl is not defined
    at n.eval (eval at m.template (underscore.js:formatted:969), <anonymous>:16:9)
    at n.c [as template] (underscore.js:formatted:975)
    at n.render (application.js:188)
    at n.renderFinding (application.js:270)
    at _ (backbone.js:formatted:284)
    at m (backbone.js:formatted:261)
    at f (backbone.js:formatted:98)
    at n.u.trigger (backbone.js:formatted:250)
    at n._onModelEvent (backbone.js:formatted:938)
    at _ (backbone.js:formatted:288)
```

My gut says that these parameter are only written based on this [code snippet](**https://github.com/N0MoreSecr3ts/wraith/blob/471568ba6b67aa3c5f2ce5435936866d1252d1ed/core/findings.go#L35**) when the mode is hooked to a service like Github/Gitlab

**Comment by Shashank-In** [comment]
yeah facing the same issue. I tried debugging this but not sure where it went wrong.

**Comment by mattyjones** [comment]
@iBotPeaches @Shashank-In The webserver piece is a work in progress, I rebuilt some of the js but due to the implementation of threading the progress bar and some of the variables are a little borked still.

What version are you running so I can check if it still exists in `develop` and if so I can make a note of it. The webserver component is high on the priority list as I find it very useful. Performance was just higher on my list and the webserver absorbed the hit. 🤷

**Comment by iBotPeaches** [comment]
> What version are you running so I can check if it still exists in `develop` and if so I can make a note of it. The webserver component is high on the priority list as I find it very useful. Performance was just higher on my list and the webserver absorbed the hit.

I was running develop at time of report, so looks like no more commits since that time.

**Comment by mattyjones** [comment]
@shreyas-sriram if you want to take a stab at this feel free. Now that you fixed the glaring issues with the web frontend, this may be a good next step. Let me know as I will tackle this otherwise.

cc @iBotPeaches @Shashank-In

**Comment by shreyas-sriram** [comment]
I ran the following and the latest develop branch works as expected. I am unable reproduce this. @iBotPeaches Did you run the same options as below?

```
./wraith scanLocalGitRepo --local-repos ~/Downloads/wraith-test --web-server --debug
```
I believe this was fixed with the recent PR - https://github.com/N0MoreSecr3ts/wraith/pull/126/files#diff-3e8602c86d6cf04a5c74b954f9f957b652617102cf8f4b647fe46989f480861dR137

**Comment by iBotPeaches** [comment]
Works now on latest develop. Must have been that commit. Closing.
