### ISSUE TITLE
Failed to load signatures file default.yml: open default.yml: no such file or directory

### ISSUE THREAD

**Issue by ghost** [N0MoreSecr3ts/wraith#54]
I get `Failed to load signatures file default.yml: open default.yml: no such file or directory` when running on an org. I have no problem with the help command.

**Comment by mattyjones** [comment]
@Nyon-spec ny Can you try building from the **develop** branch, I believe this was a known issue and was fixed. If the error still persists in that branch we can take a look further.

In order to troubleshoot more, you need to provide the command used as well as a copy of the config file (if you are using one).

Thanks!

**Comment by mattyjones** [comment]
@Nyon-spec I found the issue and fixed it with 74f73938826c8856c6da69f88d982ea01c45aadd and released it w/ 0.0.5

Once you confirm we can close this out.
