### ISSUE TITLE
Support for event-based scanning

### ISSUE THREAD

**Issue by dantecl** [N0MoreSecr3ts/wraith#80]
Hi,

Are there any plans to make wraith support event-based scanning, by monitoring the Github events API and scanning the commits? Similar to what shhgit does.

Thanks,

Dante

**Comment by mattyjones** [comment]
@dantecl Not at this time. It can be dropped into a pipeline so that when the build/release process starts it get run.

**Comment by dantecl** [comment]
Bummer. 

Well, we have multiple disparate pipelines at the moment, and I also wanted to catch stuff that does not see a pipeline build. I want to catch these commits as they happen, from a central location, and not even have to wait for a delay between a commit having a secret and an eventual build. Thanks for the clarification though.

-d

**Comment by mattyjones** [comment]
If you want to catch these right away you could rig something up with a git hook, if using git. Something along the lines of a pre receive. You could do a pre-commit which is the safest but al so the hardest.

If you want to catch pre/no pipeline commits the best way is git hooks and have them call out but you would still need a way to run the tool. Maybe a Lambda function in AWS. I would suggest a pre-recieve with the ability to do a local path scan as there is no need to keep checking the same commit history.

The issue here is that if you have multiple commits per checkin you would need to run a scan local repo command to capture all the commits. There may be a way to rig this up dynamically with a defined depth equal to the commits being checked-in.

Either way there is a fair amount of UX work to be figured out for any of these methods that should be done y someone with the big picture of the complete developer experience. Happy to offer thoughts and advice here if you want to continue to spitball ideas.

@dantecl
